name: Build, Push Docker Image, and Deploy to Minikube

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for cross-platform image building)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t hkabshire/uiservice:${{ github.sha }} .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push hkabshire/uiservice:${{ github.sha }}

      # Optional: Tag the image with `latest` and push
      - name: Tag Image with latest
        run: |
          docker tag hkabshire/uiservice:${{ github.sha }} hkabshire/uiservice:latest
          docker push hkabshire/uiservice:latest

      # Step 6: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: '1.24.0'  # Specify the version of kubectl you want to use

      # Step 7: Set up Minikube
      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      # Step 8: Configure kubectl to use Minikube
      - name: Configure kubectl
        run: |
          kubectl config set-cluster minikube --server=https://kubernetes.docker.internal:8443
          kubectl config set-context minikube --cluster=minikube --user=minikube
          kubectl config use-context minikube

      # Step 9: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml --namespace=dev
